openapi: 3.0.2
info:
    title: shop-api
    version: 1.0.0
    description: '### This is a Swagger UI for my Shop API'
paths:
    /items:
        get:
            tags:
                - items
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of items:
                                    value:
                                        -
                                            id: 1
                                            name: Samsung Galaxy S23
                                            description: Brand New
                                            category: Phones
                                            price: 999.9
                    description: ' Returns a list of items'
            summary: Get a list of all items
            description: Returns a list of all items in API
        post:
            requestBody:
                description: A new item to be created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-item'
                required: true
            tags:
                - items
            responses:
                '201':
                    content:
                        new-item: {}
                    description: Successfully created
                '400':
                    content:
                        error:
                            examples:
                                Bad Request:
                                    value: Something is missing
                    description: 'One or all params are missing. '
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error message:
                                    value:
                                        error: 'Something went wrong on our side. Sorry :('
                    description: 'Something went wrong on our side. Sorry :('
            summary: New item
            description: ''
    '/items/{id}':
        get:
            tags:
                - items
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of a given game:
                                    value: '{id:3, name: "Nvidia RTX 3070", price: 1100.99}'
                    description: Returns fill details of a given id item
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Game /w+ was not found:
                                    value:
                                        error: Item was not found
                    description: Item was not found in items array
            summary: Get full details of a given item
            description: Returns full details of a given item
        put:
            tags:
                - items
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                update:
                                    value:
                                        name: Apple Watch Series 7
                                        description: Brand new
                                        category: Watches
                                        price: 499.99
                    description: Updated
            summary: Update item
            description: Updates selected item
        delete:
            tags:
                - items
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/delete-item'
                    description: Empty
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: The item you're looking for is not here anymore
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Something went wrong
            summary: Delete item
            description: Will erase
        parameters:
            -
                name: id
                in: path
                required: true
    /users:
        get:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                list of users:
                                    value:
                                        -
                                            id: 1
                                            name: DonaldTrump
                    description: Returns a list of all users
            summary: Get a list of users
            description: Returns a list of all users
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-user'
                        examples:
                            UserName:
                                value:
                                    UserName: DesiredUserName
                required: true
            tags:
                - users
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/new-user'
                            examples:
                                NewUser:
                                    value:
                                        UserName: Josh
                    description: New user created
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Invalid Input
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Something went wrong
            summary: Create a new user
            description: Creates a new user
    '/users/{id}':
        get:
            tags:
                - users
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                User:
                                    value:
                                        -
                                            UserId: 1
                                            UserName: DonaldTrump
                    description: Done
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                not found:
                                    value:
                                        error: user not found
                    description: User not found
            summary: Returns info about user
            description: Shows user info
        put:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Update UserName:
                                    value:
                                        UserName: UserName
                    description: Updated
            summary: Update user
            description: Updates user info
        delete:
            tags:
                - users
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/delete-item'
                    description: Deleted
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: User not here anymore
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Something went wrong
            summary: Delete user
            description: Deletes user
        parameters:
            -
                name: id
                in: path
                required: true
    /reviews:
        get:
            tags:
                - reviews
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of reviews:
                                    value:
                                        - Very good
                                        - Nice
                    description: Returns a list of reviews
            summary: Get a list of all reviews
            description: Returns a list of all reviews in API
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-review'
                        examples:
                            Review:
                                value:
                                    -
                                        reviewBody: Text
                                        UserId: ''
                                        ItemId: ''
                required: true
            tags:
                - reviews
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/new-review'
                            examples:
                                Review:
                                    value:
                                        -
                                            reviewBody: Text
                                            UserId: ''
                                            ItemId: ''
                    description: |
                        Created
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: One or all Params are missing
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Something went wrong
            summary: Creates a new review
            description: New review to be created
    '/reviews/{id}':
        get:
            tags:
                - reviews
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                    description: Returs specific review
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Review was not found
            summary: Specific review
            description: ''
        delete:
            tags:
                - reviews
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/delete-item'
                    description: |
                        No content
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: No review found
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                    description: Something went wrong
            summary: Delete review
            description: Deletes selected review
        parameters:
            -
                name: id
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        delete-item:
            title: Root Type for delete-item
            description: Will remove item
            required:
                - id
            type: object
            properties:
                id:
                    format: int32
                    type: integer
            example:
                id: 1
        new-item:
            title: Root Type for new-game
            description: Try it out!
            required:
                - price
                - name
                - description
                - category
            type: object
            properties:
                name:
                    type: string
                price:
                    format: float
                    type: number
                description:
                    description: ''
                    type: string
                category:
                    description: ''
                    type: string
            example:
                name: Apple Watch Series 7
                description: Brand new
                category: Watches
                price: 499.99
        new-user:
            description: Creates a new user
            required:
                - UserName
            type: object
            properties:
                UserName:
                    description: Choose UserName
                    type: string
            example:
                UserName: DesiredUsername
        new-review:
            description: Create a review
            required:
                - reviewBody
            type: object
            properties:
                reviewBody:
                    description: ''
                    type: string
                    example: |-
                        {
                            "reviewBody": "Text",
                            "ItemId": "itemId",
                            "UserId": "userID"
                        }
            example:
                reviewBody: Text
                ItemId: itemId
                UserId: userID
