openapi: 3.0.2
info:
    title: games-api
    version: 1.0.0
    description: '### This is a Swagger UI for my Games API'
paths:
    /games:
        get:
            tags:
                - games
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of games:
                                    value:
                                        - Witcher 3
                                        - Cyberpunk 2077
                    description: ' Returns a list of games'
            summary: Get a list of all games
            description: Returns a list of all games in API
        post:
            requestBody:
                description: A new game to be created
                required: true
            tags:
                - new-game
            responses:
                '201':
                    content:
                        new-game: {}
                    description: Successfully created
                '400':
                    content:
                        error:
                            examples:
                                Bad Request:
                                    value: Something is missing
                    description: 'One or all params are missing. '
            summary: New game
            description: ''
    '/games/{id}':
        get:
            tags:
                - details
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of a given game:
                                    value: '{id:3, name: "Minecraft", price: 26.99}'
                    description: Returns fill details of a given id game
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Game /w+ was not found:
                                    value: Game \\w+ was not found in game array
                    description: Game was not found in games array
            operationId: id
            summary: Get full details of a game
            description: Returns full details of a given id game
        delete:
            requestBody:
                content:
                    delete-item: {}
                required: false
            tags:
                - delete
            responses:
                '204':
                    description: Empty
                '404':
                    description: The item you're looking for is not here anymore
            summary: Delete item
            description: Will erase
        parameters:
            -
                name: id
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        new-game:
            title: Root Type for new-game
            description: Try it out!
            required:
                - price
                - name
            type: object
            properties:
                name:
                    type: string
                price:
                    format: float
                    type: number
            example:
                name: Papers please
                price: 0.99
        delete-item:
            title: Root Type for delete-item
            description: Will remove item
            required:
                - id
            type: object
            properties:
                id:
                    format: int32
                    type: integer
            example:
                id: 1