{
    "get": {
        "tags": [
            "games"
        ],
        "responses": {
            "200": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "examples": {
                            "List of games": {
                                "value": [
                                    "Witcher 3",
                                    "Cyberpunk 2077"
                                ]
                            }
                        }
                    }
                },
                "description": " Returns a list of games"
            }
        },
        "summary": "Get a list of all games",
        "description": "Returns a list of all games in API"
    },
    "post": {
        "requestBody": {
            "description": "A new game to be created",
            "required": true
        },
        "tags": [
            "new-game"
        ],
        "responses": {
            "201": {
                "content": {
                    "new-game": {}
                },
                "description": "Successfully created"
            },
            "400": {
                "description": "One or all params are missing. "
            },
            "406": {
                "content": {
                    "error": {}
                },
                "description": "Error"
            }
        },
        "summary": "New game",
        "description": ""
    }
}